from typing import Protocol
from uuid import UUID

from identity_access_management_context.domain.entities import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def list_all(self) -> list[User]: ...

    def save(self, user: User) -> None: ...

    def delete(self, user_id: UUID) -> None: ...

    def update(self, user: User) -> None: ...

    def get_admin(self) -> User | None: ...
