repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint
        language: node
      - id: typecheck
        name: Type Checking
        entry: npm run typecheck
        language: node
        files: \.tsx?$
