apiVersion: v1
kind: Secret
metadata:
  name: {{ include "le-coffre.fullname" . }}-backend-secret
  labels:
    {{- include "le-coffre.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "le-coffre.databaseUrl" . | quote }}
  jwt-secret-key: {{ .Values.backend.secrets.jwtSecretKey | quote }}
