apiVersion: v1
kind: Service
metadata:
  name: {{ include "le-coffre.frontend.fullname" . }}
  labels:
    {{- include "le-coffre.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "le-coffre.frontend.selectorLabels" . | nindent 4 }}
