apiVersion: v1
kind: Secret
metadata:
  name: {{ include "le-coffre.fullname" . }}
  labels:
    {{- include "le-coffre.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.config.jwt.secretKey | quote }}
