{{- if or .Values.config.jwt.secretKey .Values.config.smtp.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "le-coffre.fullname" . }}
  labels:
    {{- include "le-coffre.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.jwt.secretKey }}
  JWT_SECRET_KEY: {{ .Values.config.jwt.secretKey | quote }}
  {{- end }}
  {{- if .Values.config.smtp.password }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | quote }}
  {{- end }}
{{- end }}
