/**
 * An unlock session pools the shares of one unlock ceremony on the backend.
 * Its id is generated by the unlock page and travels in the page URL, which
 * the share holders pass to each other.
 *
 * Anyone who knows the id can add shares to the session — and a single wrong
 * share spoils it — so the id must not be guessable: 16 characters of a
 * 32-letter alphabet drawn from the CSPRNG give 80 bits of entropy.
 */

// Crockford's base32 alphabet (no I, L, O, U): easy to read aloud or retype.
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
const LENGTH = 16

// Mirrors the backend's UNLOCK_SESSION_ID_PATTERN.
const UNLOCK_SESSION_ID_PATTERN = /^[A-Za-z0-9_-]{16,64}$/

export function generateUnlockSessionId(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(LENGTH))
  // 256 is a multiple of 32, so `% 32` stays uniform.
  return Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]).join('')
}

export function isValidUnlockSessionId(value: unknown): value is string {
  return typeof value === 'string' && UNLOCK_SESSION_ID_PATTERN.test(value)
}
