// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { CreateVaultApiVaultSetupPostData, CreateVaultApiVaultSetupPostResponses, CreateVaultApiVaultSetupPostErrors, UnlockVaultApiVaultUnlockPostData, UnlockVaultApiVaultUnlockPostResponses, UnlockVaultApiVaultUnlockPostErrors, LockVaultApiVaultLockPostData, LockVaultApiVaultLockPostResponses, CreatePasswordApiPasswordsPostData, CreatePasswordApiPasswordsPostResponses, CreatePasswordApiPasswordsPostErrors, GetPasswordApiPasswordsPasswordIdGetData, GetPasswordApiPasswordsPasswordIdGetResponses, GetPasswordApiPasswordsPasswordIdGetErrors, ShareAccessApiResourceIdSharePostData, ShareAccessApiResourceIdSharePostResponses, ShareAccessApiResourceIdSharePostErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new vault
 * Create a new vault with Shamir's Secret Sharing.
 *
 * - **nb_shares**: Total number of shares to generate
 * - **threshold**: Minimum number of shares needed to unlock the vault
 */
export const createVaultApiVaultSetupPost = <ThrowOnError extends boolean = false>(options: Options<CreateVaultApiVaultSetupPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateVaultApiVaultSetupPostResponses, CreateVaultApiVaultSetupPostErrors, ThrowOnError>({
        url: '/api/vault/setup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Unlock the vault
 * Unlock the vault using Shamir's Secret Sharing reconstruction.
 *
 * - **shares**: List of shares (index + secret) needed to reconstruct the master secret
 */
export const unlockVaultApiVaultUnlockPost = <ThrowOnError extends boolean = false>(options: Options<UnlockVaultApiVaultUnlockPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UnlockVaultApiVaultUnlockPostResponses, UnlockVaultApiVaultUnlockPostErrors, ThrowOnError>({
        url: '/api/vault/unlock',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Lock the vault
 * Lock the vault by clearing the decrypted key from memory.
 *
 * The vault must be unlocked to be locked again.
 */
export const lockVaultApiVaultLockPost = <ThrowOnError extends boolean = false>(options?: Options<LockVaultApiVaultLockPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LockVaultApiVaultLockPostResponses, unknown, ThrowOnError>({
        url: '/api/vault/lock',
        ...options
    });
};

/**
 * Create a new password
 * Create a new password entry.
 *
 * - **user_id**: ID of the user creating the password
 * - **name**: Name/title for the password entry
 * - **password**: The actual password to store (will be encrypted)
 * - **folder**: Optional folder to organize the password
 */
export const createPasswordApiPasswordsPost = <ThrowOnError extends boolean = false>(options: Options<CreatePasswordApiPasswordsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreatePasswordApiPasswordsPostResponses, CreatePasswordApiPasswordsPostErrors, ThrowOnError>({
        url: '/api/passwords/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get a password by ID
 * Retrieve a password by its ID with user authentication.
 *
 * - **password_id**: The ID of the password to retrieve
 * - **user_id**: ID of the user requesting access
 */
export const getPasswordApiPasswordsPasswordIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPasswordApiPasswordsPasswordIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPasswordApiPasswordsPasswordIdGetResponses, GetPasswordApiPasswordsPasswordIdGetErrors, ThrowOnError>({
        url: '/api/passwords/{password_id}',
        ...options
    });
};

/**
 * Share access to a password
 * Share access to a resource.
 *
 * - **resource_id**: The ID of the resource to share
 * - **from_id**: The ID of the user sharing the resource
 * - **to_id**: The ID of the user receiving access
 */
export const shareAccessApiResourceIdSharePost = <ThrowOnError extends boolean = false>(options: Options<ShareAccessApiResourceIdSharePostData, ThrowOnError>) => {
    return (options.client ?? client).post<ShareAccessApiResourceIdSharePostResponses, ShareAccessApiResourceIdSharePostErrors, ThrowOnError>({
        url: '/api/{resource_id}/share',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
