// This file is auto-generated by @hey-api/openapi-ts

/**
 * CreatePasswordRequest
 */
export type CreatePasswordRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * CreatePasswordResponse
 */
export type CreatePasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * CreateVaultPostRequest
 */
export type CreateVaultPostRequest = {
    /**
     * Nb Shares
     */
    nb_shares: number;
    /**
     * Threshold
     */
    threshold: number;
};

/**
 * CreateVaultPostResponse
 */
export type CreateVaultPostResponse = {
    /**
     * Shares
     */
    shares: Array<Share>;
};

/**
 * GetPasswordResponse
 */
export type GetPasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LockVaultPostResponse
 */
export type LockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * Share
 */
export type Share = {
    /**
     * Index
     */
    index: number;
    /**
     * Secret
     */
    secret: string;
};

/**
 * ShareAccessRequest
 */
export type ShareAccessRequest = {
    /**
     * From Id
     */
    from_id: string;
    /**
     * To Id
     */
    to_id: string;
};

/**
 * ShareRequest
 */
export type ShareRequest = {
    /**
     * Index
     */
    index: number;
    /**
     * Secret
     */
    secret: string;
};

/**
 * UnlockVaultPostRequest
 */
export type UnlockVaultPostRequest = {
    /**
     * Shares
     * List of shares to unlock the vault
     */
    shares: Array<ShareRequest>;
};

/**
 * UnlockVaultPostResponse
 */
export type UnlockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CreateVaultApiVaultSetupPostData = {
    body: CreateVaultPostRequest;
    path?: never;
    query?: never;
    url: '/api/vault/setup';
};

export type CreateVaultApiVaultSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVaultApiVaultSetupPostError = CreateVaultApiVaultSetupPostErrors[keyof CreateVaultApiVaultSetupPostErrors];

export type CreateVaultApiVaultSetupPostResponses = {
    /**
     * Successful Response
     */
    201: CreateVaultPostResponse;
};

export type CreateVaultApiVaultSetupPostResponse = CreateVaultApiVaultSetupPostResponses[keyof CreateVaultApiVaultSetupPostResponses];

export type UnlockVaultApiVaultUnlockPostData = {
    body: UnlockVaultPostRequest;
    path?: never;
    query?: never;
    url: '/api/vault/unlock';
};

export type UnlockVaultApiVaultUnlockPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlockVaultApiVaultUnlockPostError = UnlockVaultApiVaultUnlockPostErrors[keyof UnlockVaultApiVaultUnlockPostErrors];

export type UnlockVaultApiVaultUnlockPostResponses = {
    /**
     * Successful Response
     */
    200: UnlockVaultPostResponse;
};

export type UnlockVaultApiVaultUnlockPostResponse = UnlockVaultApiVaultUnlockPostResponses[keyof UnlockVaultApiVaultUnlockPostResponses];

export type LockVaultApiVaultLockPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vault/lock';
};

export type LockVaultApiVaultLockPostResponses = {
    /**
     * Successful Response
     */
    200: LockVaultPostResponse;
};

export type LockVaultApiVaultLockPostResponse = LockVaultApiVaultLockPostResponses[keyof LockVaultApiVaultLockPostResponses];

export type CreatePasswordApiPasswordsPostData = {
    body: CreatePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/passwords/';
};

export type CreatePasswordApiPasswordsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePasswordApiPasswordsPostError = CreatePasswordApiPasswordsPostErrors[keyof CreatePasswordApiPasswordsPostErrors];

export type CreatePasswordApiPasswordsPostResponses = {
    /**
     * Successful Response
     */
    201: CreatePasswordResponse;
};

export type CreatePasswordApiPasswordsPostResponse = CreatePasswordApiPasswordsPostResponses[keyof CreatePasswordApiPasswordsPostResponses];

export type GetPasswordApiPasswordsPasswordIdGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/passwords/{password_id}';
};

export type GetPasswordApiPasswordsPasswordIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasswordApiPasswordsPasswordIdGetError = GetPasswordApiPasswordsPasswordIdGetErrors[keyof GetPasswordApiPasswordsPasswordIdGetErrors];

export type GetPasswordApiPasswordsPasswordIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetPasswordResponse;
};

export type GetPasswordApiPasswordsPasswordIdGetResponse = GetPasswordApiPasswordsPasswordIdGetResponses[keyof GetPasswordApiPasswordsPasswordIdGetResponses];

export type ShareAccessApiResourceIdSharePostData = {
    body: ShareAccessRequest;
    path: {
        /**
         * Resource Id
         */
        resource_id: string;
    };
    query?: never;
    url: '/api/{resource_id}/share';
};

export type ShareAccessApiResourceIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareAccessApiResourceIdSharePostError = ShareAccessApiResourceIdSharePostErrors[keyof ShareAccessApiResourceIdSharePostErrors];

export type ShareAccessApiResourceIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://backend:8000' | (string & {});
};
