// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * AddMemberToGroupRequest
 */
export type AddMemberToGroupRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AddMemberToGroupResponse
 */
export type AddMemberToGroupResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AddOwnerToGroupRequest
 */
export type AddOwnerToGroupRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AddOwnerToGroupResponse
 */
export type AddOwnerToGroupResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AdminLoginRequest
 */
export type AdminLoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminLoginResponse
 */
export type AdminLoginResponse = {
    /**
     * Admin Id
     */
    admin_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ConfigureSsoProviderRequest
 *
 * Configure SSO provider with OpenID Connect auto-discovery.
 */
export type ConfigureSsoProviderRequest = {
    /**
     * Client Id
     *
     * Client ID OAuth2
     */
    client_id: string;
    /**
     * Client Secret
     *
     * Client secret OAuth2
     */
    client_secret: string;
    /**
     * Discovery Url
     *
     * OpenID Connect discovery URL (.well-known/openid_configuration)
     */
    discovery_url: string;
};

/**
 * CreateGroupRequest
 */
export type CreateGroupRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * CreateGroupResponse
 */
export type CreateGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreatePasswordRequest
 */
export type CreatePasswordRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * CreatePasswordResponse
 */
export type CreatePasswordResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * CreateVaultPostRequest
 */
export type CreateVaultPostRequest = {
    /**
     * Nb Shares
     */
    nb_shares: number;
    /**
     * Threshold
     */
    threshold: number;
};

/**
 * CreateVaultPostResponse
 */
export type CreateVaultPostResponse = {
    /**
     * Setup Id
     */
    setup_id: string;
    /**
     * Shares
     */
    shares: Array<ShareResponse>;
};

/**
 * EventData
 */
export type EventData = {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Occurred On
     */
    occurred_on: string;
    /**
     * Priority
     */
    priority: string;
};

/**
 * GetGroupResponse
 */
export type GetGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Personal
     */
    is_personal: boolean;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Owners
     */
    owners: Array<string>;
    /**
     * Members
     */
    members: Array<string>;
};

/**
 * GetPasswordListResponse
 */
export type GetPasswordListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Folder
     */
    folder: string;
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * GetPasswordResponse
 */
export type GetPasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder: string;
};

/**
 * GetUserMeResponse
 */
export type GetUserMeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Personal Group Id
     */
    personal_group_id?: string | null;
};

/**
 * GetUserResponse
 */
export type GetUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles?: Array<string>;
};

/**
 * GroupAccessItem
 */
export type GroupAccessItem = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionEnum>;
    /**
     * Is Owner
     */
    is_owner: boolean;
};

/**
 * GroupItem
 */
export type GroupItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Personal
     */
    is_personal: boolean;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Owners
     */
    owners: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IsSsoConfigSetResponse
 *
 * Response indicating if SSO is configured.
 */
export type IsSsoConfigSetResponse = {
    /**
     * Is Set
     */
    is_set: boolean;
};

/**
 * ListEventsResponse
 */
export type ListEventsResponse = {
    /**
     * Events
     */
    events: Array<EventData>;
};

/**
 * ListGroupsResponse
 */
export type ListGroupsResponse = {
    /**
     * Groups
     */
    groups: Array<GroupItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * ListPasswordAccessResponse
 */
export type ListPasswordAccessResponse = {
    /**
     * Resource Id
     */
    resource_id: string;
    /**
     * User Access List
     */
    user_access_list: Array<UserAccessItem>;
    /**
     * Group Access List
     */
    group_access_list: Array<GroupAccessItem>;
};

/**
 * ListUserResponse
 */
export type ListUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles: Array<string>;
};

/**
 * LockVaultPostResponse
 */
export type LockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * PermissionEnum
 */
export type PermissionEnum = 'read';

/**
 * RefreshAccessTokenResponse
 */
export type RefreshAccessTokenResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * RegisterAdminRequest
 */
export type RegisterAdminRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * RegisterAdminResponse
 */
export type RegisterAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * RemoveMemberFromGroupResponse
 */
export type RemoveMemberFromGroupResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * SharePasswordRequest
 */
export type SharePasswordRequest = {
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * SharePasswordResponse
 */
export type SharePasswordResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ShareResponse
 */
export type ShareResponse = {
    /**
     * Secret
     */
    secret: string;
};

/**
 * SsoCallbackResponse
 */
export type SsoCallbackResponse = {
    /**
     * Message
     */
    message: string;
    user: SsoUserInfo;
};

/**
 * SsoUserInfo
 */
export type SsoUserInfo = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is New User
     */
    is_new_user: boolean;
};

/**
 * UnlockVaultPostRequest
 */
export type UnlockVaultPostRequest = {
    /**
     * Shares
     *
     * List of share secrets (hex strings with embedded index)
     */
    shares: Array<string>;
};

/**
 * UnlockVaultPostResponse
 */
export type UnlockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UpdateGroupRequest
 */
export type UpdateGroupRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * UpdateGroupResponse
 */
export type UpdateGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * UpdatePasswordRequest
 */
export type UpdatePasswordRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * UpdateUserRequest
 */
export type UpdateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserAccessItem
 */
export type UserAccessItem = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionEnum>;
    /**
     * Is Owner
     */
    is_owner: boolean;
};

/**
 * ValidateSetupRequest
 */
export type ValidateSetupRequest = {
    /**
     * Setup Id
     */
    setup_id: string;
};

/**
 * ValidateSetupResponse
 */
export type ValidateSetupResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VaultStatus
 */
export type VaultStatus = 'LOCKED' | 'UNLOCKED' | 'NOT_SETUP' | 'PENDING' | 'SETUPED';

/**
 * VaultStatusResponse
 */
export type VaultStatusResponse = {
    status: VaultStatus;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateVaultVaultSetupPostData = {
    body: CreateVaultPostRequest;
    path?: never;
    query?: never;
    url: '/vault/setup';
};

export type CreateVaultVaultSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVaultVaultSetupPostError = CreateVaultVaultSetupPostErrors[keyof CreateVaultVaultSetupPostErrors];

export type CreateVaultVaultSetupPostResponses = {
    /**
     * Successful Response
     */
    201: CreateVaultPostResponse;
};

export type CreateVaultVaultSetupPostResponse = CreateVaultVaultSetupPostResponses[keyof CreateVaultVaultSetupPostResponses];

export type ValidateVaultSetupVaultValidateSetupPostData = {
    body: ValidateSetupRequest;
    path?: never;
    query?: never;
    url: '/vault/validate-setup';
};

export type ValidateVaultSetupVaultValidateSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateVaultSetupVaultValidateSetupPostError = ValidateVaultSetupVaultValidateSetupPostErrors[keyof ValidateVaultSetupVaultValidateSetupPostErrors];

export type ValidateVaultSetupVaultValidateSetupPostResponses = {
    /**
     * Successful Response
     */
    200: ValidateSetupResponse;
};

export type ValidateVaultSetupVaultValidateSetupPostResponse = ValidateVaultSetupVaultValidateSetupPostResponses[keyof ValidateVaultSetupVaultValidateSetupPostResponses];

export type UnlockVaultVaultUnlockPostData = {
    body: UnlockVaultPostRequest;
    path?: never;
    query?: never;
    url: '/vault/unlock';
};

export type UnlockVaultVaultUnlockPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlockVaultVaultUnlockPostError = UnlockVaultVaultUnlockPostErrors[keyof UnlockVaultVaultUnlockPostErrors];

export type UnlockVaultVaultUnlockPostResponses = {
    /**
     * Successful Response
     */
    200: UnlockVaultPostResponse;
};

export type UnlockVaultVaultUnlockPostResponse = UnlockVaultVaultUnlockPostResponses[keyof UnlockVaultVaultUnlockPostResponses];

export type LockVaultVaultLockPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vault/lock';
};

export type LockVaultVaultLockPostResponses = {
    /**
     * Successful Response
     */
    200: LockVaultPostResponse;
};

export type LockVaultVaultLockPostResponse = LockVaultVaultLockPostResponses[keyof LockVaultVaultLockPostResponses];

export type GetVaultStatusVaultStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vault/status';
};

export type GetVaultStatusVaultStatusGetResponses = {
    /**
     * Successful Response
     */
    200: VaultStatusResponse;
};

export type GetVaultStatusVaultStatusGetResponse = GetVaultStatusVaultStatusGetResponses[keyof GetVaultStatusVaultStatusGetResponses];

export type CreatePasswordPasswordsPostData = {
    body: CreatePasswordRequest;
    path?: never;
    query?: never;
    url: '/passwords/';
};

export type CreatePasswordPasswordsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePasswordPasswordsPostError = CreatePasswordPasswordsPostErrors[keyof CreatePasswordPasswordsPostErrors];

export type CreatePasswordPasswordsPostResponses = {
    /**
     * Successful Response
     */
    201: CreatePasswordResponse;
};

export type CreatePasswordPasswordsPostResponse = CreatePasswordPasswordsPostResponses[keyof CreatePasswordPasswordsPostResponses];

export type ListPasswordsPasswordsListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Folder
         */
        folder?: string | null;
    };
    url: '/passwords/list';
};

export type ListPasswordsPasswordsListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPasswordsPasswordsListGetError = ListPasswordsPasswordsListGetErrors[keyof ListPasswordsPasswordsListGetErrors];

export type ListPasswordsPasswordsListGetResponses = {
    /**
     * Response List Passwords Passwords List Get
     *
     * Successful Response
     */
    200: Array<GetPasswordListResponse>;
};

export type ListPasswordsPasswordsListGetResponse = ListPasswordsPasswordsListGetResponses[keyof ListPasswordsPasswordsListGetResponses];

export type DeletePasswordPasswordsPasswordIdDeleteData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}';
};

export type DeletePasswordPasswordsPasswordIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePasswordPasswordsPasswordIdDeleteError = DeletePasswordPasswordsPasswordIdDeleteErrors[keyof DeletePasswordPasswordsPasswordIdDeleteErrors];

export type DeletePasswordPasswordsPasswordIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePasswordPasswordsPasswordIdDeleteResponse = DeletePasswordPasswordsPasswordIdDeleteResponses[keyof DeletePasswordPasswordsPasswordIdDeleteResponses];

export type GetPasswordPasswordsPasswordIdGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}';
};

export type GetPasswordPasswordsPasswordIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasswordPasswordsPasswordIdGetError = GetPasswordPasswordsPasswordIdGetErrors[keyof GetPasswordPasswordsPasswordIdGetErrors];

export type GetPasswordPasswordsPasswordIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetPasswordResponse;
};

export type GetPasswordPasswordsPasswordIdGetResponse = GetPasswordPasswordsPasswordIdGetResponses[keyof GetPasswordPasswordsPasswordIdGetResponses];

export type UpdatePasswordPasswordsPasswordIdPutData = {
    body: UpdatePasswordRequest;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}';
};

export type UpdatePasswordPasswordsPasswordIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordPasswordsPasswordIdPutError = UpdatePasswordPasswordsPasswordIdPutErrors[keyof UpdatePasswordPasswordsPasswordIdPutErrors];

export type UpdatePasswordPasswordsPasswordIdPutResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type SharePasswordPasswordsPasswordIdSharePostData = {
    body: SharePasswordRequest;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}/share';
};

export type SharePasswordPasswordsPasswordIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SharePasswordPasswordsPasswordIdSharePostError = SharePasswordPasswordsPasswordIdSharePostErrors[keyof SharePasswordPasswordsPasswordIdSharePostErrors];

export type SharePasswordPasswordsPasswordIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: SharePasswordResponse;
};

export type SharePasswordPasswordsPasswordIdSharePostResponse = SharePasswordPasswordsPasswordIdSharePostResponses[keyof SharePasswordPasswordsPasswordIdSharePostResponses];

export type UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}/share/{group_id}';
};

export type UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteError = UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteErrors[keyof UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteErrors];

export type UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteResponse = UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteResponses[keyof UnsharePasswordPasswordsPasswordIdShareGroupIdDeleteResponses];

export type ListPasswordAccessPasswordsPasswordIdAccessGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}/access';
};

export type ListPasswordAccessPasswordsPasswordIdAccessGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPasswordAccessPasswordsPasswordIdAccessGetError = ListPasswordAccessPasswordsPasswordIdAccessGetErrors[keyof ListPasswordAccessPasswordsPasswordIdAccessGetErrors];

export type ListPasswordAccessPasswordsPasswordIdAccessGetResponses = {
    /**
     * Successful Response
     */
    200: ListPasswordAccessResponse;
};

export type ListPasswordAccessPasswordsPasswordIdAccessGetResponse = ListPasswordAccessPasswordsPasswordIdAccessGetResponses[keyof ListPasswordAccessPasswordsPasswordIdAccessGetResponses];

export type GetUserMeUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUserMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: GetUserMeResponse;
};

export type GetUserMeUsersMeGetResponse = GetUserMeUsersMeGetResponses[keyof GetUserMeUsersMeGetResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type GetUserUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUsersUserIdGetError = GetUserUsersUserIdGetErrors[keyof GetUserUsersUserIdGetErrors];

export type GetUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetUserResponse;
};

export type GetUserUsersUserIdGetResponse = GetUserUsersUserIdGetResponses[keyof GetUserUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPutData = {
    body: UpdateUserRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type ListUsersUsersGetResponses = {
    /**
     * Response List Users Users  Get
     *
     * Successful Response
     */
    200: Array<ListUserResponse>;
};

export type ListUsersUsersGetResponse = ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: CreateUserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type PromoteUserToAdminUsersUserIdPromoteAdminPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/promote-admin';
};

export type PromoteUserToAdminUsersUserIdPromoteAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PromoteUserToAdminUsersUserIdPromoteAdminPostError = PromoteUserToAdminUsersUserIdPromoteAdminPostErrors[keyof PromoteUserToAdminUsersUserIdPromoteAdminPostErrors];

export type PromoteUserToAdminUsersUserIdPromoteAdminPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PromoteUserToAdminUsersUserIdPromoteAdminPostResponse = PromoteUserToAdminUsersUserIdPromoteAdminPostResponses[keyof PromoteUserToAdminUsersUserIdPromoteAdminPostResponses];

export type AdminLoginAuthLoginPostData = {
    body: AdminLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AdminLoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminLoginAuthLoginPostError = AdminLoginAuthLoginPostErrors[keyof AdminLoginAuthLoginPostErrors];

export type AdminLoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AdminLoginResponse;
};

export type AdminLoginAuthLoginPostResponse = AdminLoginAuthLoginPostResponses[keyof AdminLoginAuthLoginPostResponses];

export type RegisterAdminAuthRegisterAdminPostData = {
    body: RegisterAdminRequest;
    path?: never;
    query?: never;
    url: '/auth/register-admin';
};

export type RegisterAdminAuthRegisterAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAdminAuthRegisterAdminPostError = RegisterAdminAuthRegisterAdminPostErrors[keyof RegisterAdminAuthRegisterAdminPostErrors];

export type RegisterAdminAuthRegisterAdminPostResponses = {
    /**
     * Successful Response
     */
    201: RegisterAdminResponse;
};

export type RegisterAdminAuthRegisterAdminPostResponse = RegisterAdminAuthRegisterAdminPostResponses[keyof RegisterAdminAuthRegisterAdminPostResponses];

export type ConfigureSsoProviderAuthSsoConfigurePostData = {
    body: ConfigureSsoProviderRequest;
    path?: never;
    query?: never;
    url: '/auth/sso/configure';
};

export type ConfigureSsoProviderAuthSsoConfigurePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfigureSsoProviderAuthSsoConfigurePostError = ConfigureSsoProviderAuthSsoConfigurePostErrors[keyof ConfigureSsoProviderAuthSsoConfigurePostErrors];

export type ConfigureSsoProviderAuthSsoConfigurePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSsoUrlAuthSsoUrlGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sso/url';
};

export type GetSsoUrlAuthSsoUrlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SsoCallbackAuthSsoCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         *
         * Authorization code from SSO provider
         */
        code: string;
        /**
         * State
         *
         * State parameter for CSRF protection
         */
        state?: string;
    };
    url: '/auth/sso/callback';
};

export type SsoCallbackAuthSsoCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SsoCallbackAuthSsoCallbackGetError = SsoCallbackAuthSsoCallbackGetErrors[keyof SsoCallbackAuthSsoCallbackGetErrors];

export type SsoCallbackAuthSsoCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: SsoCallbackResponse;
};

export type SsoCallbackAuthSsoCallbackGetResponse = SsoCallbackAuthSsoCallbackGetResponses[keyof SsoCallbackAuthSsoCallbackGetResponses];

export type IsSsoConfigSetAuthSsoIsConfiguredGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sso/is-configured';
};

export type IsSsoConfigSetAuthSsoIsConfiguredGetResponses = {
    /**
     * Successful Response
     */
    200: IsSsoConfigSetResponse;
};

export type IsSsoConfigSetAuthSsoIsConfiguredGetResponse = IsSsoConfigSetAuthSsoIsConfiguredGetResponses[keyof IsSsoConfigSetAuthSsoIsConfiguredGetResponses];

export type RefreshAccessTokenAuthRefreshTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh-token';
};

export type RefreshAccessTokenAuthRefreshTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAccessTokenAuthRefreshTokenPostError = RefreshAccessTokenAuthRefreshTokenPostErrors[keyof RefreshAccessTokenAuthRefreshTokenPostErrors];

export type RefreshAccessTokenAuthRefreshTokenPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshAccessTokenResponse;
};

export type RefreshAccessTokenAuthRefreshTokenPostResponse = RefreshAccessTokenAuthRefreshTokenPostResponses[keyof RefreshAccessTokenAuthRefreshTokenPostResponses];

export type CreateGroupGroupsPostData = {
    body: CreateGroupRequest;
    path?: never;
    query?: never;
    url: '/groups/';
};

export type CreateGroupGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupGroupsPostError = CreateGroupGroupsPostErrors[keyof CreateGroupGroupsPostErrors];

export type CreateGroupGroupsPostResponses = {
    /**
     * Successful Response
     */
    201: CreateGroupResponse;
};

export type CreateGroupGroupsPostResponse = CreateGroupGroupsPostResponses[keyof CreateGroupGroupsPostResponses];

export type AddMemberToGroupGroupsGroupIdMembersPostData = {
    body: AddMemberToGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/members';
};

export type AddMemberToGroupGroupsGroupIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberToGroupGroupsGroupIdMembersPostError = AddMemberToGroupGroupsGroupIdMembersPostErrors[keyof AddMemberToGroupGroupsGroupIdMembersPostErrors];

export type AddMemberToGroupGroupsGroupIdMembersPostResponses = {
    /**
     * Successful Response
     */
    201: AddMemberToGroupResponse;
};

export type AddMemberToGroupGroupsGroupIdMembersPostResponse = AddMemberToGroupGroupsGroupIdMembersPostResponses[keyof AddMemberToGroupGroupsGroupIdMembersPostResponses];

export type AddOwnerToGroupGroupsGroupIdOwnersPostData = {
    body: AddOwnerToGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/owners';
};

export type AddOwnerToGroupGroupsGroupIdOwnersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddOwnerToGroupGroupsGroupIdOwnersPostError = AddOwnerToGroupGroupsGroupIdOwnersPostErrors[keyof AddOwnerToGroupGroupsGroupIdOwnersPostErrors];

export type AddOwnerToGroupGroupsGroupIdOwnersPostResponses = {
    /**
     * Successful Response
     */
    201: AddOwnerToGroupResponse;
};

export type AddOwnerToGroupGroupsGroupIdOwnersPostResponse = AddOwnerToGroupGroupsGroupIdOwnersPostResponses[keyof AddOwnerToGroupGroupsGroupIdOwnersPostResponses];

export type RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/members/{user_id}';
};

export type RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteError = RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteErrors[keyof RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteErrors];

export type RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: RemoveMemberFromGroupResponse;
};

export type RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteResponse = RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteResponses[keyof RemoveMemberFromGroupGroupsGroupIdMembersUserIdDeleteResponses];

export type DeleteGroupGroupsGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type DeleteGroupGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupGroupsGroupIdDeleteError = DeleteGroupGroupsGroupIdDeleteErrors[keyof DeleteGroupGroupsGroupIdDeleteErrors];

export type DeleteGroupGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGroupGroupsGroupIdDeleteResponse = DeleteGroupGroupsGroupIdDeleteResponses[keyof DeleteGroupGroupsGroupIdDeleteResponses];

export type GetGroupGroupsGroupIdGetData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type GetGroupGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGroupGroupsGroupIdGetError = GetGroupGroupsGroupIdGetErrors[keyof GetGroupGroupsGroupIdGetErrors];

export type GetGroupGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetGroupResponse;
};

export type GetGroupGroupsGroupIdGetResponse = GetGroupGroupsGroupIdGetResponses[keyof GetGroupGroupsGroupIdGetResponses];

export type UpdateGroupGroupsGroupIdPutData = {
    body: UpdateGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type UpdateGroupGroupsGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupGroupsGroupIdPutError = UpdateGroupGroupsGroupIdPutErrors[keyof UpdateGroupGroupsGroupIdPutErrors];

export type UpdateGroupGroupsGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: UpdateGroupResponse;
};

export type UpdateGroupGroupsGroupIdPutResponse = UpdateGroupGroupsGroupIdPutResponses[keyof UpdateGroupGroupsGroupIdPutResponses];

export type ListGroupsGroupsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Personal
         *
         * Include personal groups in results. Set to false to only show shared groups.
         */
        include_personal?: boolean;
    };
    url: '/groups';
};

export type ListGroupsGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGroupsGroupsGetError = ListGroupsGroupsGetErrors[keyof ListGroupsGroupsGetErrors];

export type ListGroupsGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: ListGroupsResponse;
};

export type ListGroupsGroupsGetResponse = ListGroupsGroupsGetResponses[keyof ListGroupsGroupsGetResponses];

export type ListEventsEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Event Type
         *
         * Filter by event types
         */
        event_type?: Array<string> | null;
        /**
         * Start Date
         *
         * Filter events from this date (inclusive)
         */
        start_date?: string | null;
        /**
         * End Date
         *
         * Filter events until this date (inclusive)
         */
        end_date?: string | null;
    };
    url: '/events';
};

export type ListEventsEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsEventsGetError = ListEventsEventsGetErrors[keyof ListEventsEventsGetErrors];

export type ListEventsEventsGetResponses = {
    /**
     * Successful Response
     */
    200: ListEventsResponse;
};

export type ListEventsEventsGetResponse = ListEventsEventsGetResponses[keyof ListEventsEventsGetResponses];
