// This file is auto-generated by @hey-api/openapi-ts

/**
 * AdminLoginRequest
 */
export type AdminLoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminLoginResponse
 */
export type AdminLoginResponse = {
    /**
     * Jwt Token
     */
    jwt_token: string;
    /**
     * Admin Id
     */
    admin_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreatePasswordRequest
 */
export type CreatePasswordRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * CreatePasswordResponse
 */
export type CreatePasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreateVaultPostRequest
 */
export type CreateVaultPostRequest = {
    /**
     * Nb Shares
     */
    nb_shares: number;
    /**
     * Threshold
     */
    threshold: number;
};

/**
 * CreateVaultPostResponse
 */
export type CreateVaultPostResponse = {
    /**
     * Shares
     */
    shares: Array<Share>;
};

/**
 * GetPasswordListResponse
 */
export type GetPasswordListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * GetPasswordResponse
 */
export type GetPasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * GetUserResponse
 */
export type GetUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListUserResponse
 */
export type ListUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * LockVaultPostResponse
 */
export type LockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * RegisterAdminRequest
 */
export type RegisterAdminRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * RegisterAdminResponse
 */
export type RegisterAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * Share
 */
export type Share = {
    /**
     * Index
     */
    index: number;
    /**
     * Secret
     */
    secret: string;
};

/**
 * ShareAccessRequest
 */
export type ShareAccessRequest = {
    /**
     * From Id
     */
    from_id: string;
    /**
     * To Id
     */
    to_id: string;
};

/**
 * ShareRequest
 */
export type ShareRequest = {
    /**
     * Index
     */
    index: number;
    /**
     * Secret
     */
    secret: string;
};

/**
 * UnlockVaultPostRequest
 */
export type UnlockVaultPostRequest = {
    /**
     * Shares
     * List of shares to unlock the vault
     */
    shares: Array<ShareRequest>;
};

/**
 * UnlockVaultPostResponse
 */
export type UnlockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UpdatePasswordRequest
 */
export type UpdatePasswordRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * UpdateUserRequest
 */
export type UpdateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VaultStatus
 */
export type VaultStatus = 'LOCKED' | 'UNLOCKED' | 'NOT_SETUP';

/**
 * VaultStatusResponse
 */
export type VaultStatusResponse = {
    status: VaultStatus;
};

export type CreateVaultVaultSetupPostData = {
    body: CreateVaultPostRequest;
    path?: never;
    query?: never;
    url: '/vault/setup';
};

export type CreateVaultVaultSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVaultVaultSetupPostError = CreateVaultVaultSetupPostErrors[keyof CreateVaultVaultSetupPostErrors];

export type CreateVaultVaultSetupPostResponses = {
    /**
     * Successful Response
     */
    201: CreateVaultPostResponse;
};

export type CreateVaultVaultSetupPostResponse = CreateVaultVaultSetupPostResponses[keyof CreateVaultVaultSetupPostResponses];

export type UnlockVaultVaultUnlockPostData = {
    body: UnlockVaultPostRequest;
    headers: {
        /**
         * Authorization
         * Bearer token
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/vault/unlock';
};

export type UnlockVaultVaultUnlockPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlockVaultVaultUnlockPostError = UnlockVaultVaultUnlockPostErrors[keyof UnlockVaultVaultUnlockPostErrors];

export type UnlockVaultVaultUnlockPostResponses = {
    /**
     * Successful Response
     */
    200: UnlockVaultPostResponse;
};

export type UnlockVaultVaultUnlockPostResponse = UnlockVaultVaultUnlockPostResponses[keyof UnlockVaultVaultUnlockPostResponses];

export type LockVaultVaultLockPostData = {
    body?: never;
    headers: {
        /**
         * Authorization
         * Bearer token
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/vault/lock';
};

export type LockVaultVaultLockPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LockVaultVaultLockPostError = LockVaultVaultLockPostErrors[keyof LockVaultVaultLockPostErrors];

export type LockVaultVaultLockPostResponses = {
    /**
     * Successful Response
     */
    200: LockVaultPostResponse;
};

export type LockVaultVaultLockPostResponse = LockVaultVaultLockPostResponses[keyof LockVaultVaultLockPostResponses];

export type GetVaultStatusVaultStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vault/status';
};

export type GetVaultStatusVaultStatusGetResponses = {
    /**
     * Successful Response
     */
    200: VaultStatusResponse;
};

export type GetVaultStatusVaultStatusGetResponse = GetVaultStatusVaultStatusGetResponses[keyof GetVaultStatusVaultStatusGetResponses];

export type CreatePasswordPasswordsPostData = {
    body: CreatePasswordRequest;
    path?: never;
    query?: never;
    url: '/passwords/';
};

export type CreatePasswordPasswordsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePasswordPasswordsPostError = CreatePasswordPasswordsPostErrors[keyof CreatePasswordPasswordsPostErrors];

export type CreatePasswordPasswordsPostResponses = {
    /**
     * Successful Response
     */
    201: CreatePasswordResponse;
};

export type CreatePasswordPasswordsPostResponse = CreatePasswordPasswordsPostResponses[keyof CreatePasswordPasswordsPostResponses];

export type DeletePasswordPasswordsPasswordIdDeleteData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query: {
        /**
         * User Id
         * ID of the user deleting the password
         */
        user_id: string;
    };
    url: '/passwords/{password_id}';
};

export type DeletePasswordPasswordsPasswordIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePasswordPasswordsPasswordIdDeleteError = DeletePasswordPasswordsPasswordIdDeleteErrors[keyof DeletePasswordPasswordsPasswordIdDeleteErrors];

export type DeletePasswordPasswordsPasswordIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePasswordPasswordsPasswordIdDeleteResponse = DeletePasswordPasswordsPasswordIdDeleteResponses[keyof DeletePasswordPasswordsPasswordIdDeleteResponses];

export type GetPasswordPasswordsPasswordIdGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/passwords/{password_id}';
};

export type GetPasswordPasswordsPasswordIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasswordPasswordsPasswordIdGetError = GetPasswordPasswordsPasswordIdGetErrors[keyof GetPasswordPasswordsPasswordIdGetErrors];

export type GetPasswordPasswordsPasswordIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetPasswordResponse;
};

export type GetPasswordPasswordsPasswordIdGetResponse = GetPasswordPasswordsPasswordIdGetResponses[keyof GetPasswordPasswordsPasswordIdGetResponses];

export type UpdatePasswordPasswordsPasswordIdPutData = {
    body: UpdatePasswordRequest;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/passwords/{password_id}';
};

export type UpdatePasswordPasswordsPasswordIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordPasswordsPasswordIdPutError = UpdatePasswordPasswordsPasswordIdPutErrors[keyof UpdatePasswordPasswordsPasswordIdPutErrors];

export type UpdatePasswordPasswordsPasswordIdPutResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ListPasswordsPasswordsListFolderGetData = {
    body?: never;
    path: {
        /**
         * Folder
         */
        folder: string | null;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/passwords/list/{folder}';
};

export type ListPasswordsPasswordsListFolderGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPasswordsPasswordsListFolderGetError = ListPasswordsPasswordsListFolderGetErrors[keyof ListPasswordsPasswordsListFolderGetErrors];

export type ListPasswordsPasswordsListFolderGetResponses = {
    /**
     * Response List Passwords Passwords List  Folder  Get
     * Successful Response
     */
    200: Array<GetPasswordListResponse>;
};

export type ListPasswordsPasswordsListFolderGetResponse = ListPasswordsPasswordsListFolderGetResponses[keyof ListPasswordsPasswordsListFolderGetResponses];

export type ShareAccessResourceIdSharePostData = {
    body: ShareAccessRequest;
    path: {
        /**
         * Resource Id
         */
        resource_id: string;
    };
    query?: never;
    url: '/{resource_id}/share';
};

export type ShareAccessResourceIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareAccessResourceIdSharePostError = ShareAccessResourceIdSharePostErrors[keyof ShareAccessResourceIdSharePostErrors];

export type ShareAccessResourceIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    headers: {
        /**
         * Authorization
         * Bearer token
         */
        authorization: string;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type GetUserUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUsersUserIdGetError = GetUserUsersUserIdGetErrors[keyof GetUserUsersUserIdGetErrors];

export type GetUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetUserResponse;
};

export type GetUserUsersUserIdGetResponse = GetUserUsersUserIdGetResponses[keyof GetUserUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPutData = {
    body: UpdateUserRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type ListUsersUsersGetResponses = {
    /**
     * Response List Users Users  Get
     * Successful Response
     */
    200: Array<ListUserResponse>;
};

export type ListUsersUsersGetResponse = ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: CreateUserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type RegisterAdminAuthRegisterAdminPostData = {
    body: RegisterAdminRequest;
    path?: never;
    query?: never;
    url: '/auth/register-admin';
};

export type RegisterAdminAuthRegisterAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAdminAuthRegisterAdminPostError = RegisterAdminAuthRegisterAdminPostErrors[keyof RegisterAdminAuthRegisterAdminPostErrors];

export type RegisterAdminAuthRegisterAdminPostResponses = {
    /**
     * Successful Response
     */
    201: RegisterAdminResponse;
};

export type RegisterAdminAuthRegisterAdminPostResponse = RegisterAdminAuthRegisterAdminPostResponses[keyof RegisterAdminAuthRegisterAdminPostResponses];

export type AdminLoginAuthLoginPostData = {
    body: AdminLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AdminLoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminLoginAuthLoginPostError = AdminLoginAuthLoginPostErrors[keyof AdminLoginAuthLoginPostErrors];

export type AdminLoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AdminLoginResponse;
};

export type AdminLoginAuthLoginPostResponse = AdminLoginAuthLoginPostResponses[keyof AdminLoginAuthLoginPostResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};
