from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field

from vault_management_context.adapters.primary.fastapi.app_dependencies import (
    get_unlock_vault_usecase,
)
from vault_management_context.application.commands import UnlockVaultCommand
from vault_management_context.application.use_cases.unlock_vault_use_case import (
    UnlockVaultUseCase,
)
from vault_management_context.domain.entities.share import Share
from vault_management_context.domain.exceptions import (
    ShareReconstructionError,
    VaultManagementDomainError,
)
from vault_management_context.domain.value_objects import UNLOCK_SESSION_ID_PATTERN, UnlockSessionId

router = APIRouter(prefix="/vault", tags=["Vault"])


class UnlockVaultPostRequest(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "unlock_session_id": "ZOJRGBIZK4XQ7M2P",
                "shares": [
                    "0:abc123def456",
                    "1:def789ghi012",
                ],
            }
        }
    )

    unlock_session_id: str = Field(
        ...,
        pattern=UNLOCK_SESSION_ID_PATTERN,
        description="Id of the unlock session the shares are added to (generated by the unlock page)",
    )
    shares: list[str] = Field(
        ...,
        min_length=1,
        description="List of share secrets (hex strings with embedded index)",
    )


class UnlockVaultPostResponse(BaseModel):
    message: str


@router.post(
    "/unlock",
    response_model=UnlockVaultPostResponse,
    status_code=200,
    summary="Unlock the vault",
)
def unlock_vault(
    request: UnlockVaultPostRequest,
    usecase: UnlockVaultUseCase = Depends(get_unlock_vault_usecase),
):
    """
    Unlock the vault using Shamir's Secret Sharing reconstruction.

    This endpoint does not require authentication as it's needed to unlock the vault
    before any user can authenticate.

    - **unlock_session_id**: Id of the unlock session, shared by URL between the share holders
    - **shares**: List of share secrets (hex strings with embedded index in format "index:hexsecret")

    Shares are added to the pending shares of that unlock session only. To start over
    (e.g. after a wrong share was submitted), use a new unlock session id. Once the vault
    is unlocked, the pending shares of every session are discarded.

    Returns:
    - 200: Vault unlocked successfully
    - 202: Shares accepted and stored, but more shares needed to unlock
    - 400: Invalid shares or other domain error
    """
    try:
        # Create Share objects from secrets (index is embedded in secret)
        shares = [Share(share_secret) for share_secret in request.shares]
        command = UnlockVaultCommand(session_id=UnlockSessionId(request.unlock_session_id), shares=shares)
        usecase.execute(command)
        return {"message": "Vault unlocked successfully"}
    except ShareReconstructionError:
        # Shares were stored but insufficient to unlock
        return JSONResponse(
            status_code=202,
            content={"message": "Shares accepted. More shares needed to unlock the vault."},
        )
    except VaultManagementDomainError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal server error") from e
