FROM ghcr.io/astral-sh/uv:python3.13-alpine

RUN apk add --no-cache git bash sudo

ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=devuser

RUN addgroup -g $USER_GID $USERNAME \
    && adduser -D -u $USER_UID -G $USERNAME -s /bin/bash $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /app/server

COPY pyproject.toml ./

RUN uv sync --no-cache

COPY . .

RUN chown -R $USERNAME:$USERNAME /app

USER $USERNAME

CMD [ "tail", "-f", "/dev/null" ]
