"""Add login and url to PassWordTable

Revision ID: 443d92366c2b
Revises: d28b244c29a1
Create Date: 2026-03-05 13:06:15.766746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '443d92366c2b'
down_revision: Union[str, Sequence[str], None] = 'd28b244c29a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Password', sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Password', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Password', 'url')
    op.drop_column('Password', 'login')
    # ### end Alembic commands ###
