"""add extension token and pairing tables

Revision ID: 6783fee6d780
Revises: b7c1e9f4a2d8
Create Date: 2026-08-26 16:07:54.212433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6783fee6d780'
down_revision: Union[str, Sequence[str], None] = 'b7c1e9f4a2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExtensionPairing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('denied_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_from_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExtensionPairing_approved_by_user_id'), 'ExtensionPairing', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_ExtensionPairing_expires_at'), 'ExtensionPairing', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ExtensionPairing_id'), 'ExtensionPairing', ['id'], unique=False)
    op.create_index(op.f('ix_ExtensionPairing_user_code'), 'ExtensionPairing', ['user_code'], unique=True)
    op.create_table('ExtensionToken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_from_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExtensionToken_expires_at'), 'ExtensionToken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ExtensionToken_id'), 'ExtensionToken', ['id'], unique=False)
    op.create_index(op.f('ix_ExtensionToken_revoked_at'), 'ExtensionToken', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_ExtensionToken_token_hash'), 'ExtensionToken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_ExtensionToken_user_id'), 'ExtensionToken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ExtensionToken_user_id'), table_name='ExtensionToken')
    op.drop_index(op.f('ix_ExtensionToken_token_hash'), table_name='ExtensionToken')
    op.drop_index(op.f('ix_ExtensionToken_revoked_at'), table_name='ExtensionToken')
    op.drop_index(op.f('ix_ExtensionToken_id'), table_name='ExtensionToken')
    op.drop_index(op.f('ix_ExtensionToken_expires_at'), table_name='ExtensionToken')
    op.drop_table('ExtensionToken')
    op.drop_index(op.f('ix_ExtensionPairing_user_code'), table_name='ExtensionPairing')
    op.drop_index(op.f('ix_ExtensionPairing_id'), table_name='ExtensionPairing')
    op.drop_index(op.f('ix_ExtensionPairing_expires_at'), table_name='ExtensionPairing')
    op.drop_index(op.f('ix_ExtensionPairing_approved_by_user_id'), table_name='ExtensionPairing')
    op.drop_table('ExtensionPairing')
    # ### end Alembic commands ###
