"""add domain event table

Revision ID: 67daeaee83eb
Revises: 728072a081f9
Create Date: 2026-01-30 10:37:21.529992

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67daeaee83eb"
down_revision: Union[str, Sequence[str], None] = "728072a081f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DomainEventTable",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occurred_on", sa.DateTime(), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_DomainEventTable_event_id"),
        "DomainEventTable",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_DomainEventTable_event_id"), table_name="DomainEventTable")
    op.drop_table("DomainEventTable")
    # ### end Alembic commands ###
