"""Remove audit context table

Revision ID: 6a0a9a567a6d
Revises: 3f8a91b2c5de
Create Date: 2026-02-09 14:02:24.725094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6a0a9a567a6d'
down_revision: Union[str, Sequence[str], None] = '3f8a91b2c5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DomainEventTable_event_id'), table_name='DomainEventTable')
    op.drop_table('DomainEventTable')
    op.alter_column('password_events', 'event_data',
               existing_type=sqlite.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_events', 'event_data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.create_table('DomainEventTable',
    sa.Column('event_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('occurred_on', sa.DATETIME(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('event_data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_DomainEventTable_event_id'), 'DomainEventTable', ['event_id'], unique=False)
    # ### end Alembic commands ###
