"""add service account table

Revision ID: 6f3f296a75c9
Revises: b7c1e9f4a2d8
Create Date: 2026-09-18 09:25:23.309063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f3f296a75c9'
down_revision: Union[str, Sequence[str], None] = 'b7c1e9f4a2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ServiceAccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ServiceAccount_group_id'), 'ServiceAccount', ['group_id'], unique=False)
    op.create_index(op.f('ix_ServiceAccount_id'), 'ServiceAccount', ['id'], unique=False)
    op.create_index(op.f('ix_ServiceAccount_revoked_at'), 'ServiceAccount', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_ServiceAccount_token_hash'), 'ServiceAccount', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ServiceAccount_token_hash'), table_name='ServiceAccount')
    op.drop_index(op.f('ix_ServiceAccount_revoked_at'), table_name='ServiceAccount')
    op.drop_index(op.f('ix_ServiceAccount_id'), table_name='ServiceAccount')
    op.drop_index(op.f('ix_ServiceAccount_group_id'), table_name='ServiceAccount')
    op.drop_table('ServiceAccount')
    # ### end Alembic commands ###
