"""Initial schema with all tables

Revision ID: 728072a081f9
Revises: 
Create Date: 2026-01-22 17:20:10.723093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '728072a081f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupMemberTable',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_index(op.f('ix_GroupMemberTable_group_id'), 'GroupMemberTable', ['group_id'], unique=False)
    op.create_index(op.f('ix_GroupMemberTable_user_id'), 'GroupMemberTable', ['user_id'], unique=False)
    op.create_table('GroupTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GroupTable_id'), 'GroupTable', ['id'], unique=False)
    op.create_index(op.f('ix_GroupTable_user_id'), 'GroupTable', ['user_id'], unique=False)
    op.create_table('OwnershipTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OwnershipTable_id'), 'OwnershipTable', ['id'], unique=False)
    op.create_table('PasswordTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PasswordTable_id'), 'PasswordTable', ['id'], unique=False)
    op.create_table('PermissionsTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PermissionsTable_id'), 'PermissionsTable', ['id'], unique=False)
    op.create_table('SsoConfigurationTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discovery_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authorization_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userinfo_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jwks_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SsoUsersTable',
    sa.Column('internal_user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sso_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sso_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('internal_user_id')
    )
    op.create_index(op.f('ix_SsoUsersTable_internal_user_id'), 'SsoUsersTable', ['internal_user_id'], unique=False)
    op.create_table('UserPasswordTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserPasswordTable_id'), 'UserPasswordTable', ['id'], unique=False)
    op.create_table('UserTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserTable_id'), 'UserTable', ['id'], unique=False)
    op.create_table('vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nb_shares', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('encrypted_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('id = 1', name='only_one_vault'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault')
    op.drop_index(op.f('ix_UserTable_id'), table_name='UserTable')
    op.drop_table('UserTable')
    op.drop_index(op.f('ix_UserPasswordTable_id'), table_name='UserPasswordTable')
    op.drop_table('UserPasswordTable')
    op.drop_index(op.f('ix_SsoUsersTable_internal_user_id'), table_name='SsoUsersTable')
    op.drop_table('SsoUsersTable')
    op.drop_table('SsoConfigurationTable')
    op.drop_index(op.f('ix_PermissionsTable_id'), table_name='PermissionsTable')
    op.drop_table('PermissionsTable')
    op.drop_index(op.f('ix_PasswordTable_id'), table_name='PasswordTable')
    op.drop_table('PasswordTable')
    op.drop_index(op.f('ix_OwnershipTable_id'), table_name='OwnershipTable')
    op.drop_table('OwnershipTable')
    op.drop_index(op.f('ix_GroupTable_user_id'), table_name='GroupTable')
    op.drop_index(op.f('ix_GroupTable_id'), table_name='GroupTable')
    op.drop_table('GroupTable')
    op.drop_index(op.f('ix_GroupMemberTable_user_id'), table_name='GroupMemberTable')
    op.drop_index(op.f('ix_GroupMemberTable_group_id'), table_name='GroupMemberTable')
    op.drop_table('GroupMemberTable')
    # ### end Alembic commands ###
