"""add one time link table

Revision ID: 91d77868648a
Revises: 443d92366c2b
Create Date: 2026-07-20 12:31:25.217671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91d77868648a'
down_revision: Union[str, Sequence[str], None] = '443d92366c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OneTimeLink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OneTimeLink_created_by_user_id'), 'OneTimeLink', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_OneTimeLink_expires_at'), 'OneTimeLink', ['expires_at'], unique=False)
    op.create_index(op.f('ix_OneTimeLink_id'), 'OneTimeLink', ['id'], unique=False)
    op.create_index(op.f('ix_OneTimeLink_password_id'), 'OneTimeLink', ['password_id'], unique=False)
    op.create_index(op.f('ix_OneTimeLink_token_hash'), 'OneTimeLink', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OneTimeLink_token_hash'), table_name='OneTimeLink')
    op.drop_index(op.f('ix_OneTimeLink_password_id'), table_name='OneTimeLink')
    op.drop_index(op.f('ix_OneTimeLink_id'), table_name='OneTimeLink')
    op.drop_index(op.f('ix_OneTimeLink_expires_at'), table_name='OneTimeLink')
    op.drop_index(op.f('ix_OneTimeLink_created_by_user_id'), table_name='OneTimeLink')
    op.drop_table('OneTimeLink')
    # ### end Alembic commands ###
