"""Add Password Events Table

Revision ID: aa385458b504
Revises: 67daeaee83eb
Create Date: 2026-02-09 14:23:09.400943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa385458b504'
down_revision: Union[str, Sequence[str], None] = '67daeaee83eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_on', sa.DateTime(), nullable=False),
    sa.Column('password_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_password_events_actor_user_id'), 'password_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_password_events_event_type'), 'password_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_password_events_occurred_on'), 'password_events', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_password_events_password_id'), 'password_events', ['password_id'], unique=False)
    op.drop_index(op.f('ix_DomainEventTable_event_id'), table_name='DomainEventTable')
    op.drop_table('DomainEventTable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DomainEventTable',
    sa.Column('event_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('occurred_on', sa.DATETIME(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('event_data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_DomainEventTable_event_id'), 'DomainEventTable', ['event_id'], unique=False)
    op.drop_index(op.f('ix_password_events_password_id'), table_name='password_events')
    op.drop_index(op.f('ix_password_events_occurred_on'), table_name='password_events')
    op.drop_index(op.f('ix_password_events_event_type'), table_name='password_events')
    op.drop_index(op.f('ix_password_events_actor_user_id'), table_name='password_events')
    op.drop_table('password_events')
    # ### end Alembic commands ###
