from typing import Protocol, Optional
from uuid import UUID
from user_management_context.domain.entities import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> Optional[User]: ...

    def get_by_email(self, email: str) -> Optional[User]: ...

    def list_all(self) -> list[User]: ...

    def save(self, user: User) -> None: ...

    def delete(self, user_id: UUID) -> None: ...

    def update(self, user: User) -> None: ...

    def get_admin(self) -> Optional[User]: ...
