from .private_api_group_ownership_gateway import PrivateApiGroupOwnershipGateway
from .private_api_user_contact_gateway import PrivateApiUserContactGateway

__all__ = ["PrivateApiGroupOwnershipGateway", "PrivateApiUserContactGateway"]
