name: Generate and Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-chart-publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Publish release to GitHub
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
